In [140]:
from pytrends.request import TrendReq
from pytrends.dailydata import getDailyData
import numpy as np
import datetime

In [2]:
#proxies
# pytrends = TrendReq(hl='en-US', tz=360, timeout=(10,25), proxies=['https://34.203.233.13:80',], retries=2, backoff_factor=0.1)

In [195]:
# Login to Google. Only need to run this once, the rest of requests will use the same session.
pytrend = TrendReq(hl='en-US', tz=360)

# Create payload and capture API tokens. Only needed for interest_over_time(), interest_by_region() & related_queries()
pytrend.build_payload(kw_list=['ford'])

# Interest Over Time
interest_over_time_df = pytrend.interest_over_time()
print(interest_over_time_df)

# # Interest by Region
# interest_by_region_df = pytrend.interest_by_region()
# print(interest_by_region_df.head())

# # Related Queries, returns a dictionary of dataframes
# related_queries_dict = pytrend.related_queries()
# print(related_queries_dict)

# # Get Google Hot Trends data
# trending_searches_df = pytrend.trending_searches()
# print(trending_searches_df.head())

# # Get Google Hot Trends data
# today_searches_df = pytrend.today_searches()
# print(today_searches_df.head())

# # Get Google Top Charts
# top_charts_df = pytrend.top_charts(2018, hl='en-US', tz=300, geo='GLOBAL')
# print(top_charts_df.head())

# # Get Google Keyword Suggestions
# suggestions_dict = pytrend.suggestions(keyword='pizza')
# print(suggestions_dict)

            ford isPartial
date
2014-07-06    72     False
2014-07-13    74     False
2014-07-20    75     False
2014-07-27    75     False
2014-08-03    73     False
2014-08-10    72     False
2014-08-17    74     False
2014-08-24    73     False
2014-08-31    69     False
2014-09-07    72     False
2014-09-14    72     False
2014-09-21    71     False
2014-09-28    69     False
2014-10-05    68     False
2014-10-12    69     False
2014-10-19    71     False
2014-10-26    70     False
2014-11-02    69     False
2014-11-09    70     False
2014-11-16    71     False
2014-11-23    68     False
2014-11-30    68     False
2014-12-07    66     False
2014-12-14    66     False
2014-12-21    63     False
2014-12-28    71     False
2015-01-04    72     False
2015-01-11    79     False
2015-01-18    75     False
2015-01-25    71     False
...          ...       ...
2018-12-02    69     False
2018-12-09    67     False
2018-12-16    69     False
2018-12-23    69     False
2018-12-30    71     False
2019-01-06    74     False
2019-01-13    74     False
2019-01-20    73     False
2019-01-27    73     False
2019-02-03    77     False
2019-02-10    73     False
2019-02-17    76     False
2019-02-24    74     False
2019-03-03    74     False
2019-03-10    75     False
2019-03-17    77     False
2019-03-24    76     False
2019-03-31    74     False
2019-04-07    74     False
2019-04-14    73     False
2019-04-21    74     False
2019-04-28    71     False
2019-05-05    70     False
2019-05-12    73     False
2019-05-19    73     False
2019-05-26    69     False
2019-06-02    73     False
2019-06-09    74     False
2019-06-16    73     False
2019-06-23    74      True

[260 rows x 2 columns]

In [10]:
print(pytrends.get_historical_interest(kw_list, year_start=2015, month_start=1, day_start=1, year_end=2018, month_end=2, day_end=1, cat=0, geo='', gprop='', sleep=0))

The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
The request failed: Google returned a response with code 429.
                     Blockchain  isPartial
date
2015-01-01 00:00:00          51      False
2015-01-01 01:00:00          46      False
2015-01-01 02:00:00          45      False
2015-01-01 03:00:00          35      False
2015-01-01 04:00:00          51      False
2015-01-01 05:00:00          39      False
2015-01-01 06:00:00          53      False
2015-01-01 07:00:00          46      False
2015-01-01 08:00:00          40      False
2015-01-01 09:00:00          43      False
2015-01-01 10:00:00          48      False
2015-01-01 11:00:00          57      False
2015-01-01 12:00:00          52      False
2015-01-01 13:00:00          65      False
2015-01-01 14:00:00          46      False
2015-01-01 15:00:00          51      False
2015-01-01 16:00:00          56      False
2015-01-01 17:00:00          55      False
2015-01-01 18:00:00          51      False
2015-01-01 19:00:00          61      False
2015-01-01 20:00:00          58      False
2015-01-01 21:00:00          73      False
2015-01-01 22:00:00          64      False
2015-01-01 23:00:00          60      False
2015-01-02 00:00:00          58      False
2015-01-02 01:00:00          67      False
2015-01-02 02:00:00          49      False
2015-01-02 03:00:00          53      False
2015-01-02 04:00:00          63      False
2015-01-02 05:00:00          56      False
...                         ...        ...
2016-11-01 19:00:00          62      False
2016-11-01 20:00:00          62      False
2016-11-01 21:00:00          64      False
2016-11-01 22:00:00          65      False
2016-11-01 23:00:00          60      False
2016-11-02 00:00:00          56      False
2016-11-02 01:00:00          52      False
2016-11-02 02:00:00          55      False
2016-11-02 03:00:00          61      False
2016-11-02 04:00:00          62      False
2016-11-02 05:00:00          68      False
2016-11-02 06:00:00          72      False
2016-11-02 07:00:00          75      False
2016-11-02 08:00:00          78      False
2016-11-02 09:00:00          93      False
2016-11-02 10:00:00          87      False
2016-11-02 11:00:00          74      False
2016-11-02 12:00:00          75      False
2016-11-02 13:00:00          78      False
2016-11-02 14:00:00          78      False
2016-11-02 15:00:00          77      False
2016-11-02 16:00:00          68      False
2016-11-02 17:00:00          65      False
2016-11-02 18:00:00          64      False
2016-11-02 19:00:00          63      False
2016-11-02 20:00:00          67      False
2016-11-02 21:00:00          65      False
2016-11-02 22:00:00          58      False
2016-11-02 23:00:00          57      False
2016-11-03 00:00:00          51      False

[16224 rows x 2 columns]

In [71]:
df = getDailyData(word= 'ford',
                 start_year = 2015,
                 stop_year = 2018,
                 verbose = True,
                 wait_time = 5.0)

setup
built payload

In [72]:
df = df.reset_index()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209 entries, 0 to 208
Data columns (total 3 columns):
date         209 non-null datetime64[ns]
ford         209 non-null int64
isPartial    209 non-null bool
dtypes: bool(1), datetime64[ns](1), int64(1)
memory usage: 3.5 KB

In [137]:
master_df = pd.DataFrame(index=date_list)

In [142]:
master_df.loc[datetime.date(year=2015,month=1,day=1):datetime.date(year=2015,month=1,day=11)]

Empty DataFrame
Columns: []
Index: [2015-01-01, 2015-01-02, 2015-01-03, 2015-01-04, 2015-01-05, 2015-01-06, 2015-01-07, 2015-01-08, 2015-01-09, 2015-01-10, 2015-01-11]

In [114]:
type(date_list[0])

datetime.date

In [192]:
from datetime import date, timedelta
def create_date_list(start=date(2015, 1, 1),end=date(2019, 6, 30)):
    #creates a list of dates between d1 and d2 to use as an index for the google trends dataframe
    d1 = start  # start date
    d2 = end  # end date

    delta = d2 - d1         # timedelta
    date_list = []
    for i in range(delta.days + 1):
        date_list.append(d1 + timedelta(days=i))
    return date_list

In [73]:
df['ford'].iloc[0], df['date'].iloc[0]

(49, Timestamp('2015-01-04 00:00:00'))

In [74]:
(df['date'].iloc[1] - df['date'].iloc[0]).days

7

In [75]:
(df['ford'].iloc[1] - df['ford'].iloc[0])  / (df['date'].iloc[1] - df['date'].iloc[0]).days

1.1428571428571428

In [190]:
def build_complete_trends(df,company):
    temp = np.zeros((df['date'].iloc[len(df)-1] - df['date'].iloc[0]).days+1)
    tot = 0
    for i in range(0,len(df['date'])):
        try:
            counter = (df['date'].iloc[i+1] - df['date'].iloc[i]).days     
            temp[tot]=df[str(company)][i]
            multiplier = 0
            for j in range(0,counter):
                adder = (df[str(company)].iloc[i+1] - df[str(company)].iloc[i])  / (df['date'].iloc[i+1] - df['date'].iloc[i]).days
                tot+=1
                multiplier +=1
                temp[tot]=df[str(company)].iloc[i]+adder * multiplier
        except:
            continue
    return temp

In [154]:

d1 = date(2015, 1, 1)  # start date
d2 = date(2019, 6, 30)  # end date

delta = d2 - d1         # timedelta
date_list = []
for i in range(delta.days + 1)
for 
master_df.at[datetime.date(year=2015,month=1,day=1), 'Ford'] = 10

In [124]:
dfl = pd.DataFrame(np.random.randn(5, 4),
                   columns=list('ABCD'),
                  index=pd.date_range('20130101', periods=5))

In [130]:
dfl.index[0]

Timestamp('2013-01-01 00:00:00', freq='D')

In [159]:
df

          date  ford  isPartial
0   2015-01-04    49      False
1   2015-01-11    57      False
2   2015-01-18    53      False
3   2015-01-25    51      False
4   2015-02-01    51      False
5   2015-02-08    52      False
6   2015-02-15    52      False
7   2015-02-22    51      False
8   2015-03-01    69      False
9   2015-03-08    57      False
10  2015-03-15    54      False
11  2015-03-22    54      False
12  2015-03-29    52      False
13  2015-04-05    51      False
14  2015-04-12    53      False
15  2015-04-19    53      False
16  2015-04-26    52      False
17  2015-05-03    51      False
18  2015-05-10    53      False
19  2015-05-17    53      False
20  2015-05-24    55      False
21  2015-05-31    53      False
22  2015-06-07    54      False
23  2015-06-14    55      False
24  2015-06-21    58      False
25  2015-06-28    56      False
26  2015-07-05    56      False
27  2015-07-12    58      False
28  2015-07-19    56      False
29  2015-07-26    60      False
..         ...   ...        ...
179 2018-06-10    59      False
180 2018-06-17    59      False
181 2018-06-24    59      False
182 2018-07-01    59      False
183 2018-07-08    62      False
184 2018-07-15    61      False
185 2018-07-22    61      False
186 2018-07-29    61      False
187 2018-08-05    60      False
188 2018-08-12    60      False
189 2018-08-19    59      False
190 2018-08-26    58      False
191 2018-09-02    57      False
192 2018-09-09    54      False
193 2018-09-16    74      False
194 2018-09-23   100      False
195 2018-09-30    76      False
196 2018-10-07    61      False
197 2018-10-14    55      False
198 2018-10-21    55      False
199 2018-10-28    55      False
200 2018-11-04    54      False
201 2018-11-11    55      False
202 2018-11-18    55      False
203 2018-11-25    53      False
204 2018-12-02    55      False
205 2018-12-09    53      False
206 2018-12-16    55      False
207 2018-12-23    56      False
208 2018-12-30    55      False

[209 rows x 3 columns]

In [118]:
master_df

Empty DataFrame
Columns: []
Index: [2015-01-01, 2015-01-02, 2015-01-03, 2015-01-04, 2015-01-05, 2015-01-06, 2015-01-07, 2015-01-08, 2015-01-09, 2015-01-10, 2015-01-11, 2015-01-12, 2015-01-13, 2015-01-14, 2015-01-15, 2015-01-16, 2015-01-17, 2015-01-18, 2015-01-19, 2015-01-20, 2015-01-21, 2015-01-22, 2015-01-23, 2015-01-24, 2015-01-25, 2015-01-26, 2015-01-27, 2015-01-28, 2015-01-29, 2015-01-30, 2015-01-31, 2015-02-01, 2015-02-02, 2015-02-03, 2015-02-04, 2015-02-05, 2015-02-06, 2015-02-07, 2015-02-08, 2015-02-09, 2015-02-10, 2015-02-11, 2015-02-12, 2015-02-13, 2015-02-14, 2015-02-15, 2015-02-16, 2015-02-17, 2015-02-18, 2015-02-19, 2015-02-20, 2015-02-21, 2015-02-22, 2015-02-23, 2015-02-24, 2015-02-25, 2015-02-26, 2015-02-27, 2015-02-28, 2015-03-01, 2015-03-02, 2015-03-03, 2015-03-04, 2015-03-05, 2015-03-06, 2015-03-07, 2015-03-08, 2015-03-09, 2015-03-10, 2015-03-11, 2015-03-12, 2015-03-13, 2015-03-14, 2015-03-15, 2015-03-16, 2015-03-17, 2015-03-18, 2015-03-19, 2015-03-20, 2015-03-21, 2015-03-22, 2015-03-23, 2015-03-24, 2015-03-25, 2015-03-26, 2015-03-27, 2015-03-28, 2015-03-29, 2015-03-30, 2015-03-31, 2015-04-01, 2015-04-02, 2015-04-03, 2015-04-04, 2015-04-05, 2015-04-06, 2015-04-07, 2015-04-08, 2015-04-09, 2015-04-10, ...]

[1642 rows x 0 columns]

In [9]:
from datetime import date, timedelta
from functools import partial
from time import sleep

import pandas as pd

from pytrends.exceptions import ResponseError
from pytrends.request import TrendReq


def getLastDateOfMonth(year: int, month: int) -> date:
    """Given a year and a month returns an instance of the date class
    containing the last day of the corresponding month.

    Source: https://stackoverflow.com/a/43088/1445572
    """
    if month == 12:
        # last day of year is always 31st
        return date(year, month, 31)
    else:
        # go to the next month 1st day, and move back 1 day
        return date(year, month + 1, 1) - timedelta(days=1)


def getTimeframe(start: date, stop: date) -> str:
    """Given two dates, returns a stringified version of the interval between
    the two dates which is used to retrieve data for a specific time frame
    from Google Trends.
    """
    return f"{start.strftime('%Y-%m-%d')} {stop.strftime('%Y-%m-%d')}"


def _fetchData(pytrends, build_payload, timeframe: str) -> pd.DataFrame:
    """Attempts to fecth data and retries in case of a ResponseError."""
    attempts, fetched = 0, False
    while not fetched:
        try:
            build_payload(timeframe=timeframe)
        except ResponseError as err:
            print(err)
            print(f'Trying again in {60 + 5 * attempts} seconds.')
            sleep(60 + 5 * attempts)
            attempts += 1
        else:
            fetched = True
    return pytrends.interest_over_time()


def getDailyData(word: str,
                 start_year: int = 2007,
                 stop_year: int = 2018,
                 verbose: bool = True,
                 wait_time: float = 5.0) -> pd.DataFrame:
    """Given a word, fetches daily search volume data from Google Trends and
    returns results in a pandas DataFrame.

    Details: Due to the way Google Trends scales and returns data, special
    care needs to be taken to make the daily data comparable over different
    months. To do that, we download daily data on a month by month basis,
    and also monthly data. The monthly data is downloaded in one go, so that
    the monthly values are comparable amongst themselves and can be used to
    scale the daily data. The daily data is scaled by multiplying the daily
    value by the monthly search volume divided by 100.
    For a more detailed explanation see http://bit.ly/trendsscaling

    Args:
        word (str): Word to fetch daily data for.
        start_year (int): First year to fetch data for. Starts at the beginning
            of this year (1st of January).
        stop_year (int): Last year to fetch data for (inclusive). Stops at the
            end of this year (31st of December).
        verbose (bool): If True, then prints the word and current time frame
            we are fecthing the data for.

    Returns:
        complete (pd.DataFrame): Contains 4 columns.
            The column named after the word argument contains the daily search
            volume already scaled and comparable through time.
            The column f'{word}_unscaled' is the original daily data fetched
            month by month, and it is not comparable across different months
            (but is comparable within a month).
            The column f'{word}_monthly' contains the original monthly data
            fetched at once. The values in this column have been backfilled
            so that there are no NaN present.
            The column 'scale' contains the scale used to obtain the scaled
            daily data.
    """
    print("setup")
    # Set up start and stop dates
    start_date = date(start_year, 1, 1)
    stop_date = date(stop_year, 12, 31)

    # Start pytrends for US region
    pytrends = TrendReq(hl='en-US', tz=360)
    # Initialize build_payload with the word we need data for
    build_payload = partial(pytrends.build_payload,
                            kw_list=[word], cat=0, geo='US', gprop='')
    print("built payload")
    # Obtain monthly data for all months in years [start_year, stop_year]
    monthly = _fetchData(pytrends, build_payload,
                         getTimeframe(start_date, stop_date))
    return monthly